name: sticker_import
description: VK to TG Sticker Import
version: 2.0.0+10
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  vkget:
    git: 
      url: https://github.com/Sominemo/VkGet.git
      path: vkget
  flutter_svg: ^1.0.3
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  path: ^1.8.0
  enough_convert: ^1.4.0
  emoji_picker_flutter: ^1.1.1
  device_info_plus: ^3.2.1

dev_dependencies:
  lints: ^1.0.1
  intl_utils: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: l10n/

flutter_icons:
  android: true
  image_path: assets/icon-full.png
  adaptive_icon_background: "#FFECED"
  adaptive_icon_foreground: assets/icon.png

flutter_native_splash:
  ios: false
  color: "#FFECED"
  image: assets/icon-splash.png
  color_dark: "#000000"
  image_dark: assets/icon-splash-dark.png
